create or replace package ACCIDENTE_tapi
is

type ACCIDENTE_tapi_rec is record (
IDACCIDENTE  ACCIDENTE.IDACCIDENTE%type
,NPLACA  ACCIDENTE.NPLACA%type
,HORA  ACCIDENTE.HORA%type
,FECHA  ACCIDENTE.FECHA%type
,IDAGENTE  ACCIDENTE.IDAGENTE%type
,DESCRIPCION  ACCIDENTE.DESCRIPCION%type
);
type ACCIDENTE_tapi_tab is table of ACCIDENTE_tapi_rec;

-- insert
procedure ins (
p_IDACCIDENTE in ACCIDENTE.IDACCIDENTE%type
,p_NPLACA in ACCIDENTE.NPLACA%type
,p_HORA in ACCIDENTE.HORA%type
,p_FECHA in ACCIDENTE.FECHA%type
,p_IDAGENTE in ACCIDENTE.IDAGENTE%type
,p_DESCRIPCION in ACCIDENTE.DESCRIPCION%type
);
-- update
procedure upd (
p_IDACCIDENTE in ACCIDENTE.IDACCIDENTE%type
,p_NPLACA in ACCIDENTE.NPLACA%type
,p_HORA in ACCIDENTE.HORA%type
,p_FECHA in ACCIDENTE.FECHA%type
,p_IDAGENTE in ACCIDENTE.IDAGENTE%type
,p_DESCRIPCION in ACCIDENTE.DESCRIPCION%type
);
-- delete
procedure del (
p_IDACCIDENTE in ACCIDENTE.IDACCIDENTE%type
);
end ACCIDENTE_tapi;

/
create or replace package body ACCIDENTE_tapi
is
-- insert
procedure ins (
p_IDACCIDENTE in ACCIDENTE.IDACCIDENTE%type
,p_NPLACA in ACCIDENTE.NPLACA%type
,p_HORA in ACCIDENTE.HORA%type
,p_FECHA in ACCIDENTE.FECHA%type
,p_IDAGENTE in ACCIDENTE.IDAGENTE%type
,p_DESCRIPCION in ACCIDENTE.DESCRIPCION%type
) is
begin
insert into ACCIDENTE(
IDACCIDENTE
,NPLACA
,HORA
,FECHA
,IDAGENTE
,DESCRIPCION
) values (
p_IDACCIDENTE
,p_NPLACA
,p_HORA
,p_FECHA
,p_IDAGENTE
,p_DESCRIPCION
);end;
-- update
procedure upd (
p_IDACCIDENTE in ACCIDENTE.IDACCIDENTE%type
,p_NPLACA in ACCIDENTE.NPLACA%type
,p_HORA in ACCIDENTE.HORA%type
,p_FECHA in ACCIDENTE.FECHA%type
,p_IDAGENTE in ACCIDENTE.IDAGENTE%type
,p_DESCRIPCION in ACCIDENTE.DESCRIPCION%type
) is
begin
update ACCIDENTE set
NPLACA = p_NPLACA
,HORA = p_HORA
,FECHA = p_FECHA
,IDAGENTE = p_IDAGENTE
,DESCRIPCION = p_DESCRIPCION
where IDACCIDENTE = p_IDACCIDENTE;
end;
-- del
procedure del (
p_IDACCIDENTE in ACCIDENTE.IDACCIDENTE%type
) is
begin
delete from ACCIDENTE
where IDACCIDENTE = p_IDACCIDENTE;
end;
end ACCIDENTE_tapi;
